[workspace]

members = [
    "crates/*",
]


[package]
name = "shurlix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.5"
dioxus-ssr = "0.5"



